xcodebuild:
	xcodebuild -verbose -project DevelopmentApp.xcodeproj -scheme CompositeOperations clean test

xctool:
	xctool -project DevelopmentApp.xcodeproj \
	       -scheme CompositeOperations \
				 -sdk iphonesimulator \
				 clean test
