
platform :osx, '10.8'

target :DevelopmentApp, :exclusive => true do
  pod 'Kiwi'
  pod 'NSOperationQueueController', :git => 'https://github.com/stanislaw/NSOperationQueueController'
end

target :Tests, :exclusive => true do
  pod 'Kiwi'
  pod 'NSOperationQueueController', :git => 'https://github.com/stanislaw/NSOperationQueueController'
end
