
platform :osx, '10.7'

target :DevelopmentApp, :exclusive => true do
  pod 'Kiwi'
  pod 'NSOperationQueueController', :git => 'https://github.com/stanislaw/NSOperationQueueController'
end

target :CompositeOperationsTests, :exclusive => true do
  pod 'Kiwi'
  pod 'NSOperationQueueController', :git => 'https://github.com/stanislaw/NSOperationQueueController'
end
